FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /source

COPY client/. ./client/
COPY protos/. ./protos/
WORKDIR /source/client
RUN dotnet publish -c release -o /app

# final stage/image
FROM mcr.microsoft.com/dotnet/aspnet:6.0
WORKDIR /app
COPY --from=build /app ./
ENTRYPOINT ["dotnet", "client.dll"]
